import Footer from "@/components/footer";
import "./globals.css";
import { Barlow } from "next/font/google";
import Nav from "@/components/nav";
import NewUserTicker from "@/components/ticker/new-user";
import StoreProvider from "./StoreProvider";
import AuthProvider from "@/components/auth/AuthProvider";
import { Toaster } from "@/components/ui/toaster";
import ApolloClientProvider from "./ApolloProvider";

const barlow = Barlow({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <StoreProvider>
        <ApolloClientProvider>
          <AuthProvider>
            <body className={barlow.className}>
              <NewUserTicker />
              <Nav />
              {children}
              <Footer />
              <Toaster />
            </body>
          </AuthProvider>
        </ApolloClientProvider>
      </StoreProvider>
    </html>
  );
}
